name: Deploy to Staging
on:
  push:
    branches:
      - main
jobs:
  redeploy_everything:
    name:Deploying everrything to staging:
    runs-on: ubuntu-latest

    steps:
    - name: SSH into server
    - run: |
        ssh -i ${{ secrets.PRIVATE_SECRET_KEY}} ubuntu@15.207.221.106
        cd turbo-devops && git pull
        pnpm install
        pnpm run build
        pm2 restart all


