name: Deploy to Staging
on:
  push:
    branches: [main]
      
jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everrything to staging
    steps:
      - run: |
          ssh -i ${{ secrets.PRIVATE_SECRET_KEY}} ubuntu@15.207.221.106
          cd turbo-devops && git pull
          pnpm install
          pnpm run build
          pm2 restart all


